# Generated by Django 3.2.8 on 2022-12-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Project Description')),
                ('stage', models.CharField(choices=[('STD', 'STARTED'), ('CMPT', 'COMPLETED'), ('ONG', 'ONGOING')], max_length=20)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
