# Generated by Django 3.0.6 on 2022-12-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.CharField(blank=True, max_length=30, verbose_name='Contributors (Comma separated)'),
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.CharField(blank=True, max_length=100, verbose_name='Video Link'),
        ),
    ]
