# Generated by Django 3.0.6 on 2022-12-07 08:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ML', 'MACHINE LEARNING'), ('DS', 'DATA SCIENCE'), ('DA', 'DATA ANALYTICS/ANALYSIS'), ('BKD', 'BACKEND'), ('FTD', 'FRONTEND'), ('MB', 'MOBILE'), ('DB', 'DATA BASE'), ('BCH', 'BLOCKCHAIN'), ('CLD', 'CLOUD COMPUTING'), ('CWK', 'COMPUTER NETWORKING'), ('SPT', 'SCRIPTING'), ('DKP', 'DESKTOP'), ('SFT', 'SOFTWARE DEVELOPMENT'), ('GMD', 'GAME DEVELOPMENT')], default='BACKEND', max_length=50),
        ),
    ]
