# Generated by Django 4.1.4 on 2022-12-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(
                default="Niger", max_length=70, verbose_name="Country"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="state",
            field=models.CharField(
                default="State", max_length=70, verbose_name="Country"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="contributors",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Contributors"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="keywords",
            field=models.CharField(max_length=100, verbose_name="Tech Stack"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, max_length=150, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(max_length=70, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="experience_years",
            field=models.IntegerField(verbose_name="Years of Experience"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="job_title",
            field=models.CharField(
                help_text="e.g. Data Engineer", max_length=100, verbose_name="Job title"
            ),
        ),
    ]
