# Generated by Django 3.0.6 on 2022-12-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221216_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contributors (Comma separated)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.URLField(blank=True, max_length=150, verbose_name='Video Link'),
        ),
    ]
