# Generated by Django 3.0.6 on 2022-12-16 00:57

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221216_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=embed_video.fields.EmbedVideoField(verbose_name='Video Link'),
        ),
    ]
