# Generated by Django 3.0.6 on 2022-12-17 13:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221216_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Video Link'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Job Title')),
                ('organization', models.CharField(max_length=200, verbose_name='Oranization')),
                ('specific_duties', ckeditor.fields.RichTextField(verbose_name='Specific Duties')),
                ('work_started', models.DateField(blank=True, verbose_name='Dated Started')),
                ('work_ended', models.DateField(blank=True, verbose_name='Date Ended')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, verbose_name='Gender')),
                ('picture', models.ImageField(blank=True, upload_to='profile_pictures/', verbose_name='Profile Picture')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('about', ckeditor.fields.RichTextField(blank=True, default='None', max_length=500, verbose_name='About Me')),
                ('address', models.CharField(blank=True, default='None', max_length=150, verbose_name='Address')),
                ('title', models.CharField(help_text='Data Engineer', max_length=100, verbose_name='Job title')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, default='None', max_length=150, verbose_name='Facebook')),
                ('twiiter', models.URLField(blank=True, default='None', max_length=150, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, default='None', max_length=150, verbose_name='LinkedIn')),
                ('stackoverflow', models.URLField(blank=True, default='None', max_length=150, verbose_name='Stackoverflow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Publication Title')),
                ('date', models.DateField(blank=True, verbose_name='Publication Date')),
                ('link', models.URLField(blank=True, verbose_name='Publication Link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('High School', 'High School'), ('Diploma', 'Diploma'), ('Associate', 'Associate'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Others', 'Others'), ('None', 'None')], max_length=50, verbose_name='Degree')),
                ('course', models.CharField(blank=True, max_length=100, verbose_name='Course Studied')),
                ('school', models.CharField(blank=True, max_length=150, verbose_name='Institution')),
                ('grade', models.CharField(blank=True, max_length=15, verbose_name='Grade')),
                ('year', models.DateField(blank=True, verbose_name='Year of Graduation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
