# Generated by Django 3.0.6 on 2022-12-08 09:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221208_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MACHINE LEARNING', 'MACHINE LEARNING'), ('DATA SCIENCE', 'DATA SCIENCE'), ('DATA ANALYTICS/ANALYSIS', 'DATA ANALYTICS/ANALYSIS'), ('BACKEND', 'BACKEND'), ('FRONTEND', 'FRONTEND'), ('MOBILE', 'MOBILE'), ('DATA BASE', 'DATA BASE'), ('BLOCKCHAIN', 'BLOCKCHAIN'), ('CLOUD COMPUTING', 'CLOUD COMPUTING'), ('COMPUTER NETWORKING', 'COMPUTER NETWORKING'), ('SCRIPTING', 'SCRIPTING'), ('DESKTOP', 'DESKTOP'), ('SOFTWARE DEVELOPMENT', 'SOFTWARE DEVELOPMENT'), ('GAME DEVELOPMENT', 'GAME DEVELOPMENT')], default='BACKEND', max_length=190, verbose_name='Project Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Project Images'),
        ),
    ]
