# Generated by Django 3.0.6 on 2022-12-08 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20221208_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Project Images')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
        ),
    ]
